build:
	yarn run build .env.production.local, .env.production, .env.local, .env

start-server:
	serve -s build -l 3000

build-run-server:
	build start-server

start-local-server:
	yarn start .env.development.local, .env.development, .env.local, .env
